export const REFORMS_CONTROL_VALUE_CHANGED = 'REFORMS_CONTROL_VALUE_CHANGED';
export const REFORMS_CONTROL_SOILED = 'REFORMS_CONTROL_SOILED';
export const REFORMS_BEGIN_SUBMISSION = 'REFORMS_BEGIN_SUBMISSION';
export const REFORMS_END_SUBMISSION = 'REFORMS_END_SUBMISSION';
